Created the Intake Subsystem
ligerbots/RapidReact2022 pull request #1
Opened 2022-01-16 20:41 UTC by YJ-7274

2022-01-16 21:27 UTC, prensing commented
Looks fine.

2022-01-16 21:40 UTC, prensing approved these changes
YJ, please use the "m_" for the class variables

2022-01-16 21:42 UTC, prensing requested changes

2022-01-16 21:42 UTC, prensing commented on src/main/java/frc/robot/subsystems/Intake.java
> +    CANSparkMax intakeMotor;
This is a member variable, should be "m_"

2022-01-16 21:44 UTC, prensing requested changes

2022-01-16 21:44 UTC, prensing commented on src/main/java/frc/robot/subsystems/Intake.java
> +    public void IntakeCargo() {
Method start with a lowercase letter.

2022-01-17 00:18 UTC, prensing approved these changes
Looks good now.

2022-01-17 00:40 UTC, coachFitz0807 approved these changes

2022-01-17 00:41 UTC, merged