Implemented ShooterCommand, bound it to buttons
ligerbots/RapidReact2022 pull request #19
Opened 2022-02-24 02:20 UTC by Weq511762338

2022-02-24 04:13 UTC, coachFitz0807 commented
Pretty good. Just check Vision status before reading the distance.

2022-02-25 15:21 UTC, prensing requested changes

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/Constants.java
> +    public static final double INTAKE_WAIT_TIME = 0.5;
SHOTS_WAIT_TIME and INTAKE_WAIT_TIME are poor names. INTAKE_WAIT_TIME does not even mention shooting.
Maybe use "SHOOTER_BALL1_WAIT_TIME" and "SHOOTER_BALL2_WAIT_TIME"?

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/commands/ShooterCommand.java
> +        m_state = State.SPEED_UP_SHOOTER;
This is the wrong start state.

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/commands/ShooterCommand.java
> +                break;
This should be a fall-through. make sure to include a comment.

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/commands/ShooterCommand.java
> +            // State.WAIT_FOR_INTAKE checked in isFinished method
This should be an actual case statement. That will get rid of the warning at the "switch" line.

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/Constants.java
> +    public static final double INTAKE_WAIT_TIME = 0.5;
Also need to update the comments to match the usage.

2022-02-25 15:21 UTC, prensing commented on src/main/java/frc/robot/commands/ShooterCommand.java
> +                break;
Unfortunately, I think we want a timeout on this state. The vision might not be working and we don't want to wait forever. I think you can use a LigerTimer with maybe 2 seconds, but it does not need to be a Constants number. If it times out, use 9 ft for the distance (should be local constant in the class).

2022-02-27 22:43 UTC, prensing approved these changes

2022-02-27 22:43 UTC, merged