add DriveTrain Simulation
ligerbots/RapidReact2022 pull request #9
Opened 2022-01-20 03:12 UTC by Weq511762338

2022-01-20 14:40 UTC, prensing requested changes
Jack, please remove the simgui JSON files from the checkin. Those are dependent on the user and machine. You probably should put them in the .gitignore file.

2022-01-20 14:40 UTC, prensing commented on src/main/java/frc/robot/RobotContainer.java
> +      return m_xbox.getLeftX();
Please switch this to the right joystick per our spec.

2022-01-20 14:40 UTC, prensing commented on src/main/java/frc/robot/subsystems/DriveTrain.java
> +import edu.wpi.first.wpilibj.smartdashboard.FieldObject2d;
Some of these new imports are not used. Please remove them.

2022-01-20 14:48 UTC, Weq511762338 commented
Can you explain how to put them to into the gitignore file? Those files always are generated when I tried to run the simulation

2022-01-20 14:54 UTC, prensing commented
Edit the file ".gitignore" and just list them. It is a simple text file. Each line is a file name, or file name pattern, which will be ignored.

2022-01-22 04:11 UTC, coachFitz0807 approved these changes
Looks good as a start.

2022-01-22 04:11 UTC, merged